#
#
#echo -e "\e[36m>>>>>>>Install Mongo Client <<<<<<<<<<\e[0m"
#yum install mongodb-org-shell -y &>>${log}
#func_exit_status
#echo -e "\e[36m>>>>>>>Load user schema<<<<<<<<<<\e[0m"
#mongo --host mongodb.devops999.store </app/schema/${component}.js &>>${log}
#func_exit_status
#fi
#
#


- name: Install mysql Client
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: Load schema
  ansible.builtin.shell: mysql -h mysql-dev.devops999.store -uroot -pRoboShop@1 < /app/schema/{{component}}.sql

