#echo -e "\e[36m>>>>>>>Create  ${component} service file<<<<<<<<<<\e[0m"
#cp ${component}.service /etc/systemd/system/${component}.service &>>${log}
#func_exit_status
#
#cp mongo.repo /etc/yum.repos.d/mongo.repo &>>${log}
#func_exit_status
#echo -e "\e[36m>>>>>>>Create  Node Js Repos<<<<<<<<<<\e[0m"
#curl -sL https://rpm.nodesource.com/setup_lts.x | bash &>>${log}
#func_exit_status
#echo -e "\e[36m>>>>>>>Install Node js<<<<<<<<<<\e[0m"
#yum install nodejs -y &>>${log}
#func_exit_status
#func_apppreq
#func_exit_status
#echo -e "\e[36m>>>>>>>Download NodeJs Dependencies<<<<<<<<<<\e[0m"
#
#npm install &>>${log}
#func_exit_status
#echo -e "\e[36m>>>>>>>Install Mongodb Client<<<<<<<<<<\e[0m"
#func_exit_status
#func_schema_setup
#
#func_systemd


- name: copy Mongodb yum repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: install Nodejs repos
  ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x | bash

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: App Pre-reqisites
  ansible.builtin.import_tasks: app-preq.yml

- name: Download Nodejs dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Schema setup
  ansible.builtin.import_tasks: app-preq.yml